steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/insurancereport:$SHORT_SHA', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/${PROJECT_ID}/insurancereport:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'insurance'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--image=gcr.io/${PROJECT_ID}/insurancereport:$SHORT_SHA'
  env:
    - 'CLOUDSDK_CORE_DISABLE_PROMPTS=1'  # Disable prompts during deployment



    
